# Required
version: 2

# Image to use
build:
  image: testing

# Configuration
python:
  version: {{cookiecutter.python_version}}
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
